services:
  parser:
    build: .
    container_name: oe-cqm-parsers
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MONGO_URL=mongodb://mongo:27017/cqm
      # Ruby debug configuration
      - RUBY_DEBUG_HOST=0.0.0.0
      - RUBY_DEBUG_PORT=1234
      #- RUBYOPT=-r debug/open_nonstop
      - VSAC_API_KEY=09e3ffe7-8cb4-4185-b417-d2064cac83a4
      - APP_CONFIG={ 'vsac'=> {  'auth_url'=> 'https://vsac.nlm.nih.gov/vsac/ws', 'content_url' => 'https://vsac.nlm.nih.gov/vsac/svs', 'utility_url' => 'https://vsac.nlm.nih.gov/vsac', 'default_profile' => 'eCQM Update 2019-05-10'}}
    ports:
      # Expose debug port for RubyMine
      - "1234:1234"
    depends_on:
      - mongo
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
